CREATE TABLE RECORD(
  ID_RECORD NUMBER(5)PRIMARY KEY,
  MOVEMENTS VARCHAR2(3)
);

CREATE TABLE MOVEMENT(
  ID_MOVEMENT number(5) PRIMARY KEY, 
  ID_MATCH number(5), 
  ID_BOARD number(5), 
  INITIAL_COORD varchar2(4), 
  FINAL_COORD varchar2(4), 
  COLOR_TURN_P varchar2(1), 
  ID_WHITE_P number(5), 
  ID_BLACK_P number(5)
);

CREATE TABLE BOARD(
  ID_BOARD NUMBER(5),
  ID_CELL varchar2(2) NOT NULL,
  FILL number(1) NOT NULL,
  ID_PIECE varchar2(3) NULL
);

CREATE TABLE PLAYERS(
  ID_PLAYER NUMBER(5) PRIMARY KEY,
  PLAYER_NAME VARCHAR2(30),
  WINS NUMBER(3),
  LOSE NUMBER(3),
  TOTAL_MATCHS NUMBER(3),
  PERCENT NUMBER(3,2)
);

CREATE SEQUENCE playersSQ START WITH 1;

CREATE OR REPLACE TRIGGER playersT 
  BEFORE INSERT ON PLAYERS 
  FOR EACH ROW

  BEGIN
    SELECT playersSQ.NEXTVAL
    INTO   :new.ID_PLAYER
    FROM   dual;
END;
/

CREATE TABLE MATCHS(
  ID_MATCH NUMBER(5) PRIMARY KEY,
  ID_WHITE_P NUMBER(5),
  ID_BLACK_P NUMBER(5),
  ID_BOARD NUMBER(5),
  ID_RECORD NUMBER(5),
  ID_WINNER NUMBER(5),
  ID_LOSER NUMBER(5),
  GAME_STATE varchar2(10),
  COLOR_TURN_P varchar2(1),
  ID_PLAYER_1 NUMBER(5),
  ID_PLAYER_2 NUMBER(5)
);

CREATE SEQUENCE matchs_seq START WITH 1;

CREATE OR REPLACE TRIGGER matchT 
  BEFORE INSERT ON MATCHS 
  FOR EACH ROW

  BEGIN
    SELECT matchs_seq.NEXTVAL
    INTO   :new.ID_MATCH
    FROM   dual;
END;
/

INSERT INTO MOVEMENT (ID_MOVEMENT, ID_MATCH, ID_BOARD, INITIAL_COORD, FINAL_COORD, COLOR_TURN_P, ID_WHITE_P, ID_BLACK_P) VALUES (0,0,0,'','','',0,0);
--ALTER TABLE MATCHS ADD CONSTRAINT  FK_ID_RECORD FOREIGN KEY(ID_RECORD) REFERENCES RECORD(ID_RECORD);
--ALTER TABLE MATCHS ADD CONSTRAINT  FK_idBoard FOREIGN KEY(ID_BOARD) REFERENCES BOARD(ID_BOARD);
ALTER TABLE MATCHS ADD CONSTRAINT  FK_idPlayer1 FOREIGN KEY(ID_PLAYER_1) REFERENCES PLAYERS(ID_PLAYER);
ALTER TABLE MATCHS ADD CONSTRAINT  FK_idPlayer2 FOREIGN KEY(ID_PLAYER_2) REFERENCES PLAYERS(ID_PLAYER);
--ALTER TABLE MATCHS ADD CONSTRAINT  FK_ID_WINNER FOREIGN KEY(ID_WINNER) REFERENCES PLAYERS(ID_PLAYER);
--ALTER TABLE MATCHS ADD CONSTRAINT  FK_ID_LOSER FOREIGN KEY(ID_LOSER) REFERENCES PLAYERS(ID_PLAYER);

